Repository forseti-security/terraform-google-forseti, pull requests merged in 2019-08, with the labels that each got.

#220 Regenerate documentation for Terraform 0.12
  README.md
  examples/external_ip/README.md
  examples/install_simple/README.md
  examples/real_time_enforcer/README.md
  examples/shared_vpc/README.md
  examples/simple_example/README.md
Labels: cla: yes, enhancement

#223 Added support for tracing
  main.tf
  modules/server/main.tf
  modules/server/templates/scripts/forseti-server/forseti_env.sh.tpl
  modules/server/templates/scripts/forseti-server/forseti_server_startup_script.sh.tpl
  modules/server/variables.tf
  variables.tf
Labels: cla: yes

#211 Set inventory email to false and check for missing sendgrid key
  CHANGELOG.md
  README.md
  docs/upgrading_to_v4.0.md
  main.tf
  variables.tf
Labels: cla: yes

#217 Add note about requiring internet connectivity
  examples/install_simple/tutorial.md
  examples/install_simple/variables.tf
Labels: cla: yes

#215 Point to Cloud Shell tutorial in main README
  README.md
Labels: cla: yes

#216 Extract network setup from examples
  Makefile
  examples/real_time_enforcer/main.tf
  examples/real_time_enforcer/nat.tf
  examples/real_time_enforcer/variables.tf
  examples/shared_vpc/main.tf
  examples/simple_example/main.tf
  examples/simple_example/variables.tf
  test/ci/shared-vpc.yml
  test/ci/simple-example.yml
  test/ci_integration.sh
  test/fixtures/real_time_enforcer/main.tf
  test/fixtures/real_time_enforcer/variables.tf
  test/fixtures/shared_vpc/main.tf
  test/fixtures/simple_example/main.tf
  test/fixtures/simple_example/variables.tf
Labels: bug, cla: yes

#224 Revert "Added support for tracing"
  main.tf
  modules/server/main.tf
  modules/server/templates/scripts/forseti-server/forseti_env.sh.tpl
  modules/server/templates/scripts/forseti-server/forseti_server_startup_script.sh.tpl
  modules/server/variables.tf
  variables.tf
Labels: cla: yes

#213 Added excluded_resources variable in the server config file.
  README.md
  main.tf
  modules/server/main.tf
  modules/server/templates/configs/forseti_conf_server.yaml.tpl
  modules/server/variables.tf
  variables.tf
Labels: cla: yes

#225 [FORSETI RELEASE] Update Forseti version to v2.19.0
  CHANGELOG.md
  README.md
  examples/on_gke_end_to_end/variables.tf
  examples/on_gke_existing_gke_cluster/variables.tf
  examples/on_gke_new_gke_cluster/variables.tf
  modules/client/variables.tf
  modules/on_gke/variables.tf
  modules/server/variables.tf
  test/integration/simple_example/controls/client.rb
  test/integration/simple_example/controls/server.rb
  variables.tf
Labels: cla: yes

#227 Update CHANGELOG with links
  CHANGELOG.md
Labels: cla: yes

#231 Added server dependencies on IAM
  modules/server/main.tf
Labels: cla: yes

#232 Added boot disk type and boot disk size variables. Increased default disk size.
  README.md
  main.tf
  modules/server/main.tf
  modules/server/variables.tf
  variables.tf
Labels: cla: yes
