Repository forseti-security/terraform-google-forseti, pull requests merged in 2019-07, with the labels that each got.

#180 Add private IP config to Forseti enforcer VM
  .kitchen.yml
  CHANGELOG.md
  examples/real_time_enforcer/README.md
  examples/real_time_enforcer/main.tf
  examples/real_time_enforcer/nat.tf
  examples/real_time_enforcer/outputs.tf
  modules/real_time_enforcer/main.tf
  modules/real_time_enforcer/outputs.tf
  modules/real_time_enforcer/variables.tf
  test/fixtures/real_time_enforcer/main.tf
  test/fixtures/real_time_enforcer/outputs.tf
Labels: cla: yes, enhancement

#199 Drop requirement for an exported service account key
  examples/real_time_enforcer/README.md
  examples/real_time_enforcer/main.tf
  examples/real_time_enforcer/variables.tf
  test/README.md
  test/fixtures/real_time_enforcer/main.tf
  test/fixtures/real_time_enforcer/variables.tf
  test/fixtures/real_time_enforcer_roles/main.tf
  test/fixtures/real_time_enforcer_roles/variables.tf
Labels: cla: yes

#200 Updated TF changes for Forseti release 2.18.0.
  CHANGELOG.md
  README.md
  modules/client/variables.tf
  modules/rules/templates/rules/ke_rules.yaml
  modules/server/variables.tf
  variables.tf
Labels: cla: yes

#207 Adding parameter to google_sql_user resource
  modules/server/main.tf
  modules/server/variables.tf
  variables.tf
Labels: cla: no

#186 Cloud Shell installation tutorial
  examples/install_simple/.gitignore
  examples/install_simple/README.md
  examples/install_simple/backend.tf
  examples/install_simple/main.tf
  examples/install_simple/outputs.tf
  examples/install_simple/terraform.tfvars
  examples/install_simple/tutorial.md
  examples/install_simple/variables.tf
  examples/install_simple/versions.tf
Labels: cla: yes
