Repository forseti-security/terraform-google-forseti, pull requests merged in 2019-06, with the labels that each got.

#176 Fix tests
  .kitchen.yml
  test/integration/simple_example/controls/client.rb
  test/integration/simple_example/controls/server.rb
Labels: bug, cla: yes

#175 Update cloud-init.yml
  modules/real_time_enforcer/templates/cloud-init.yml
Labels: cla: yes, enhancement

#174 Optional email configs
  CHANGELOG.md
  README.md
  examples/simple_example/README.md
  examples/simple_example/main.tf
  examples/simple_example/variables.tf
  main.tf
  modules/server/main.tf
  modules/server/templates/configs/forseti_conf_server.yaml.tpl
Labels: cla: yes, enhancement

#181 Output CloudSQL Connection String
  modules/server/outputs.tf
  outputs.tf
Labels: cla: yes

#185 Update README.md
  README.md
Labels: cla: yes

#184 Release v2.17.0
  CHANGELOG.md
  README.md
  modules/server/templates/configs/forseti_conf_server.yaml.tpl
  modules/server/variables.tf
  test/integration/simple_example/controls/client.rb
  test/integration/simple_example/controls/server.rb
  variables.tf
Labels: cla: yes

#188 Update tutorial.md
  examples/install_simple/tutorial.md
Labels: cla: yes

#189 Add next steps links
  examples/install_simple/tutorial.md
Labels: cla: yes

#190 Use ci_integration, extend wait for Forseti, suppress output errors
  .gitignore
  .kitchen.yml
  Makefile
  test/fixtures/simple_example/scripts/wait-for-forseti.sh
Labels: bug, cla: yes

#168 Add Slack webhook support.
  main.tf
  modules/server/main.tf
  modules/server/templates/configs/forseti_conf_server.yaml.tpl
  modules/server/variables.tf
  test/integration/simple_example/controls/server.rb
  variables.tf
Labels: cla: yes

#194 Fix typo in groups_settings_violations template
  modules/server/templates/configs/forseti_conf_server.yaml.tpl
Labels: cla: yes

#196 Fix default resource_rules.yaml
  modules/rules/templates/rules/resource_rules.yaml
Labels: cla: yes

#192 Set default variable values to support non org installs
  README.md
  main.tf
  variables.tf
Labels: cla: yes

#195 Add Template provider requirement
  README.md
Labels: cla: yes
